### ISSUE TITLE
[Debian 10] Closing Terminal Kills MacLinuxUtils

### ISSUE THREAD

**Issue by wolfiediscord** [datcuandrei/MacLinuxUtils#2]
Hello. I am running Debian 10 with XFCE. When I close the terminal as the instructions say so, it doesn't stay running in the background. It also provides no way of getting back to the main window when it is closed. My specs are listed below

- Mac: Macbook 4,1
- Distro: Debian 10 
- DE: XFCE 4.12
- Terminal: xfce-terminal
- MacLinuxUtils Version: 2.0
- JDK Version: 11.0.8

**Comment by datcuandrei** [comment]
Hello,Wolfie!

Thank you for using MacLinuxUtils.May I ask what version of xfce-terminal are you using?

**Comment by wolfiediscord** [comment]
> Hello,Wolfie!
> 
> Thank you for using MacLinuxUtils.May I ask what version of xfce-terminal are you using?

I am using xfce-terminal version 0.8.7.4.

**Comment by datcuandrei** [comment]
<b>EDIT</b> : The shell script that launched the program has been updated.After launching the program,the terminal now doesn't depend on the program's process anymore and can be closed without interrupting it.If you have been experiencing this issue,please redownload the program.
