### ISSUE TITLE
MacLinuxUtils fails to run - Java class error

### ISSUE THREAD

**Issue by RadioactiveSharPei** [datcuandrei/MacLinuxUtils#3]
I just installed maclinuxutils 2.4 on Linux Mint 21.1.  When I try to start it via the menu icon I get a popup asking me to authenticate as root so it can run 'env', but then quits.

If I run it via command line I can see the error:

/bin/maclinuxutils 
Error: LinkageError occurred while loading main class andreid.maclinuxutils
	java.lang.UnsupportedClassVersionError: andreid/maclinuxutils has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0

I'm not sure what version of Java I need to have installed on here.
Any ideas?

**Comment by datcuandrei** [comment]
Hi there! 

First of all, thank you for using MacLinuxUtils.

Secondly, as the description of MacLinuxUtils says under the Requirements section, you need to have the latest version of Java that is available. If I remember correctly, I have compiled MacLinuxUtils with OpenJDK 16. I recommend you to download the latest JDK version that is available.

If you encounter any other issues, please let me know.
